version: '3'

services:

  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: 7.4.1
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
    networks:
      - elk

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: 7.4.1
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - 5601:5601
    expose:
      - 5601
    networks:
      - elk
    depends_on:
      - elasticsearch

  malik-montana:
    build:
      context: .
    depends_on:
      - elasticsearch
    ports:
      - 8080:8080
    expose:
      - 8080
    environment:
      - malik.timeStart=2019-10-23T14:00:00+00:00
      - malik.timeEnd=2019-10-23T16:00:00+00:00
      - malik.priceFactor=0.5
      - elasticsearch.hosts=elasticsearch:9200

networks:

  elk:
    driver: bridge