elasticsearch:
  hosts: localhost:9200
  connectTimeout: 10000
  socketTimeout: 10000

server:
  port: 8081
  servlet:
    context-path: /
logging:
  level:
    root: debug


spring:
  main:
    allow-bean-definition-overriding: true
  jackson:
    serialization:
      write_dates_as_timestamps: false
