elasticsearch:
  hosts: localhost:9200
  connectTimeout: 10000
  socketTimeout: 10000

malik:
    timeStart: 2019-10-23T14:00:00+00:00
    timeEnd: 2019-10-23T16:00:00+00:00
    priceFactor: 0.5
server:
  port: 8080
  servlet:
    context-path: /
logging:
  level:
    root: debug


spring:
  main:
    allow-bean-definition-overriding: true